# elasticsearch-values.yaml - Minikube optimized
replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

esJavaOpts: "-Xmx256m -Xms256m"

persistence:
  enabled: false

clusterName: "elasticsearch"
nodeGroup: "master"

xpack:
  security:
    enabled: false

antiAffinity: "soft"

sysctlInitContainer:
  enabled: false

esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: false