# elasticsearch-values.yaml - AWS EKS optimized
replicas: 3
minimumMasterNodes: 2

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

esJavaOpts: "-Xmx1g -Xms1g"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 30Gi

clusterName: "elasticsearch"
nodeGroup: "master"

xpack:
  security:
    enabled: false

antiAffinity: "hard"

esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    network.host: 0.0.0.0
    xpack.security.enabled: false
    cluster.initial_master_nodes: elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2