# elasticsearch-values.yaml - Single node for testing
replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

esJavaOpts: "-Xmx512m -Xms512m"

persistence:
  enabled: false

clusterName: "elasticsearch"
nodeGroup: "master"

xpack:
  security:
    enabled: false

antiAffinity: "soft"

esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false