# kibana-values.yaml
---
# Resource configuration for Minikube
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Elasticsearch connection
elasticsearchHosts: "http://elasticsearch-master:9200"

# Service configuration using ClusterIP
service:
  type: ClusterIP
  port: 5601

# Health checks
healthCheckPath: "/app/kibana"

# Basic configuration
kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: kibana
    elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true

# Security settings
podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

# Single replica for Minikube
replicas: 1

# Environment variables
env:
  - name: SERVER_HOST
    value: "0.0.0.0"
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch-master:9200"