# kibana-values.yaml - AWS EKS optimized
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

elasticsearchHosts: "http://elasticsearch-master:9200"

service:
  type: LoadBalancer
  port: 5601
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

healthCheckPath: "/app/kibana"

kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: kibana
    elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

replicas: 2

env:
  - name: SERVER_HOST
    value: "0.0.0.0"
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch-master:9200"